on: {"push":{"branches":[main]}}
jobs:
  build:
    name: nix flake check
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: slippi-nix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: nix flake check
      uses: DeterminateSystems/flake-checker-action@v4
