on: {"pull_request":{},"push":{}}
jobs:
  build:
    name: nix flake check
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: nix flake check
      uses: DeterminateSystems/flake-checker-action@v4
