on:
  push: {"branches":["**","!main"]}
  pull_request: {"branches":["main"]}
jobs:
  build:
    name: nix flake check
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: nix flake check
      uses: DeterminateSystems/flake-checker-action@v4
